C FUNCTION DMEAN is the bridge between the Discrete environment and the
C real FUNCTION MEAN.

      DOUBLE PRECISION FUNCTION DMEAN (PER,TRAIT,PAR,NPAR,VARDATA,NVAR
     1,NTOT,MALE)
      DOUBLE PRECISION PAR(NPAR),VARDATA(NVAR,NTOT)
      INTEGER TRAIT,PER
      LOGICAL MALE

      DOUBLE PRECISION EXTRA(10),MEAN
      INTEGER NEXTRA,NTRAIT,PED

C EXTRA isn't actually used
      NEXTRA = 10
C PED isn't used
      PED = 1
C NTRAIT isn't used
      NTRAIT = 1

      DMEAN=MEAN(EXTRA,PAR,VARDATA(1,PER),NEXTRA,NPAR,NTRAIT,NVAR,PED
     1,PER,TRAIT,MALE)
      END
