      FUNCTION GAMLOG(X)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     THIS ROUTINE COMPUTES LOG(GAMMA(X)) VIA A RECURRENCE RELATION
C     AND STIRLING'S FORMULA. 
C
      Y=X-1.D0
      F=SQRT(8.D0*ATAN(1.D0))
 10   IF (Y.LT.10.D0) THEN
      Y=Y+1.D0
      F=F/Y
      GO TO 10
      END IF
      GAMLOG=LOG(F)+(Y+.5D0)*LOG(Y)-Y+1.D0/(12.D0*Y)-1.D0/(360.D0*Y**3)
      END
