      SUBROUTINE MBLANK(STRING)
C
C     THIS SUBROUTINE MOVES ALL BLANKS IN A CHARACTER STRING TO
C     THE RIGHT END OF THE STRING.
C
      CHARACTER C*1,STRING*(*)
      I=1
      DO 10 J=1,LEN(STRING)
      IF (STRING(J:J).NE.' ') THEN
      C=STRING(I:I)
      STRING(I:I)=STRING(J:J)
      STRING(J:J)=C
      I=I+1
      END IF
 10   CONTINUE
      END
