      SUBROUTINE SCOR(DF,SCORE,F,LOGLIK,MAXPAR,NPAR,TRAVEL)
C
C     THIS SUBROUTINE IS NECESSARY BECAUSE THE OPTIMIZATION CODE
C     MINIMIZES MINUS THE LOGLIKELIHOOD.  FOR OUTPUT PURPOSES, THE
C     FUNCTION VALUE AND DIFFERENTIAL MUST BE CHANGED IN SIGN.
C
      DOUBLE PRECISION DF(MAXPAR),SCORE(MAXPAR),F,LOGLIK
      CHARACTER*8 TRAVEL
C
      LOGLIK=-F
C
C     IF THE GRID OPTION IS SELECTED, THEN SET THE SCORE VECTOR TO
C     ZERO.
C
      IF (TRAVEL(1:1).EQ.'G') THEN
      DO 10 I=1,NPAR
 10   SCORE(I)=0.0D0
C
      ELSE
      DO 20 I=1,NPAR
 20   SCORE(I)=-DF(I)
      END IF
      END
