      SUBROUTINE SWEEP(TABLE,WORK,K,MAXTAB,NTAB,INV)
C
C     THIS SUBROUTINE SWEEPS OR INVERSE SWEEPS ON THE KTH
C     DIAGONAL ELEMENT OF THE TABLEAU TABLE.  SET INV TO FALSE
C     FOR SWEEP AND TO TRUE FOR INVERSE SWEEP.  OPERATIONS ARE
C     CARRIED OUT ON ONLY THE UPPER TRIANGULAR PART OF TABLE.
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DOUBLE PRECISION TABLE(MAXTAB,MAXTAB),WORK(MAXTAB)
      LOGICAL INV
C
C     CALL SHOWTAB(TABLE,NTAB,0)
      DO 10 I=1,K
      WORK(I)=TABLE(I,K)
 10   TABLE(I,K)=0.0D0
      DO 20 I=K+1,NTAB
      WORK(I)=TABLE(K,I)
 20   TABLE(K,I)=0.0D0
      S=WORK(K)
      IF (INV) THEN
      WORK(K)=1.0D0
      ELSE
      WORK(K)=-1.0D0
      END IF
      DO 30 J=1,NTAB
      W=WORK(J)
      IF (W.EQ.0.0D0) GO TO 30
      DO 40 I=1,J
 40   TABLE(I,J)=TABLE(I,J)-WORK(I)*W/S
 30   CONTINUE
C     CALL SHOWTAB(TABLE,NTAB,1)
      END
