      FUNCTION TDIST(X,P)
C
C     THIS FUNCTION SUBROUTINE COMPUTES THE T CUMULATIVE DISTRIBUTION
C     AT THE POINT X FOR DEGREES OF FREEDOM P.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      TDIST=FDIST(X*X,1.D0,P)
      IF (X.GE.0.D0) THEN
      TDIST=.5D0*(1.D0+TDIST)
      ELSE
      TDIST=.5D0*(1.D0-TDIST)
      END IF
      END
