      SUBROUTINE UPCASE(STRING)
C
C     THIS SUBROUTINE CONVERTS LOWER CASE LETTERS INTO UPPER CASE
C     LETTERS.
C
      CHARACTER STRING*(*)
C
      M=ICHAR('a')
      N=ICHAR('A')
      DO 10 I=1,LEN(STRING)
      J=ICHAR(STRING(I:I))-M
 10   IF (J.GE.0.AND.J.LE.25) STRING(I:I)=CHAR(N+J)
      END
