      SUBROUTINE YESNO(M,LINE,DECIDE)
C
C     THIS SUBROUTINE INSERTS A 'YES' OR 'NO' INTO THE GIVEN LINE.
C
      CHARACTER LINE*80
      LOGICAL DECIDE
C
      IF (DECIDE) THEN
      LINE(M:80)='YES'
      ELSE
      LINE(M:80)='NO'
      END IF
      END      
